# Generated by Django 4.2.1 on 2023-06-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('local', models.CharField(max_length=100, verbose_name='local')),
                ('data', models.DateField(verbose_name='data')),
                ('horario', models.DateTimeField(verbose_name='horario')),
            ],
        ),
    ]
