# Generated by Django 4.2.1 on 2023-06-02 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_evento_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='local',
            field=models.CharField(max_length=100, null=True, verbose_name='local'),
        ),
    ]
