# Generated by Django 4.2.1 on 2023-06-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_alter_evento_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateField(null=True, verbose_name='data'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.DateTimeField(null=True, verbose_name='horario'),
        ),
    ]
