# Generated by Django 4.1.7 on 2023-06-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0004_alter_evento_data_alter_evento_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='horario',
            field=models.TimeField(null=True, verbose_name='horario'),
        ),
    ]
