# Generated by Django 4.2.3 on 2023-07-06 01:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evento', '0006_evento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
